const REGISTER = "REGISTER";
const LOGIN = "LOGIN";
const REGISTER_HOSPITAL = "REGISTER_HOSPITAL";
const CHILD_REGISTRATION = "CHILD_REGISTRATION";
const LOGOUT = "LOGOUT";

module.exports = { REGISTER, LOGIN, REGISTER_HOSPITAL, LOGOUT , CHILD_REGISTRATION };
